### ISSUE TITLE
Kanban Project Review

### ISSUE THREAD

**Issue by manq2010** [manq2010/catalog-of-my-things#25]
[Catalog of Things Project](https://github.com/manq2010/catalog-of-my-things)

The team comprises 3 team member

- Team member 1 - @manq2010 
- Team member 2 - @Ibnballo1 
- Team member 3 - @AhmedMohsen600

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @manq2010, @AhmedMohsen600 and @Ibnballo1,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by manq2010** [comment]
Thanks for the review
